version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: numerom_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=numerom
    networks:
      - numerom_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: numerom_backend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env
    depends_on:
      - mongodb
    networks:
      - numerom_network
    environment:
      - MONGO_URL=mongodb://mongodb:27017

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: numerom_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - numerom_network

volumes:
  mongodb_data:

networks:
  numerom_network:
    driver: bridge
